### ISSUE TITLE
bug! when "add 4 apr 2150 project meeting" 2150 is thought to be year

### ISSUE THREAD

**Issue by angiesasmita** [cs2103jan2015-f10-3c/main#253]
![image](https://cloud.githubusercontent.com/assets/10851617/6985488/9927e37a-da66-11e4-8273-f8136880b8cf.png)

**Comment by angiesasmita** [comment]
suggestion: change to exception

**Comment by ChunhanYu** [comment]
but this one is hard to change. The only way is user don't input such an ambiguous statement
even use exception, it is hard to define the condition. How the parser knows which one is year and which one is task desc

**Comment by ChunhanYu** [comment]
In your part, you defined 1900<year<2100?
In my part, I defined 2000<year<3000. That's why.
How about both of us define 2000<year<2100?

**Comment by angiesasmita** [comment]
okay!

**Comment by angiesasmita** [comment]
updated, but the error still persists 
![image](https://cloud.githubusercontent.com/assets/10851617/6992061/de902420-daea-11e4-9238-1d001afd6fc3.png)
