### ISSUE TITLE
!! undo for "clear" is not working!!

### ISSUE THREAD

**Issue by YangXiaozhou** [cs2103jan2015-f10-3c/main#274]

**Comment by YangXiaozhou** [comment]
you need to updateLatestVector() inside LocalStorage::clearDataList(). 
At least, that's what I think where went wrong. but I could be wrong.

**Comment by angiesasmita** [comment]
done. thanks for the clue

**Comment by YangXiaozhou** [comment]
solved? OMG thank you! how about undo edit?

**Comment by angiesasmita** [comment]
working on it! btw good job on UI
