### ISSUE TITLE
!! "undo" for "edit" is also not working properly.. !!

### ISSUE THREAD

**Issue by YangXiaozhou** [cs2103jan2015-f10-3c/main#275]
this happened in V0.4, in V0.3 it is still fine.

**Comment by angiesasmita** [comment]
wait. it got sth to do with dataProcessor update. because just before I merge, i still can do undo for clear just fine

**Comment by angiesasmita** [comment]
okay this is very weird.
I change back a minor change in dataProcessor.cpp from:

```
Storing         storing; 
vector<Data>    latestVector = storing.getLatestVector();
string          latestCommand = storing.getLatestCommand();
Data            latestData = storing.getLatestData();
```

to: 
Data latestData;
    string latestCommand;
    vector<Data> latestVector;
    Storing storing; 

```
latestVector = storing.getLatestVector();
latestCommand = storing.getLatestCommand();
latestData = storing.getLatestData();
```

and it solves the problem.
