### ISSUE TITLE
'undone' bug

### ISSUE THREAD

**Issue by kevin-christian** [cs2103jan2015-f10-3c/main#276]
The undone is unsuccessfull
the task being undone is still shown when we type 'show done' and not shown on the list of uncompleted task.
example:
'show done'
1. task 1

'undone 1'
task 1 is reopened

You have no task for today

'show done'
1. task 1

'show today'
You have no task for today

**Comment by angiesasmita** [comment]
cause undone feature is not up yet lol

**Comment by YangXiaozhou** [comment]
for me, it's up.

**Comment by kevin-christian** [comment]
haha, ok :D
