### ISSUE TITLE
weird display after undo clear

### ISSUE THREAD

**Issue by angiesasmita** [cs2103jan2015-f10-3c/main#278]
@kevin-christian @YangXiaozhou 
after undo clearing it shows "show float"

**Comment by YangXiaozhou** [comment]
huh, i don't get it here leh.

**Comment by angiesasmita** [comment]
i mean it show all the floating tasks. instead of default display

**Comment by YangXiaozhou** [comment]
yeah, i understand your meaning. I mean I don't get the weird display in my pc.

**Comment by YangXiaozhou** [comment]
is this solved? @angelitasasmita

**Comment by angiesasmita** [comment]
okay i don't have that anymore :)
