### ISSUE TITLE
undo feature of undone not exist

### ISSUE THREAD

**Issue by angiesasmita** [cs2103jan2015-f10-3c/main#280]

**Comment by YangXiaozhou** [comment]
okay, DataProcessor already supports undo undone. but O/C doesn't support yet.

**Comment by kevin-christian** [comment]
i dont think it has something to do with O/C, O/C's job is just to call the executeUndo from DataProcessor

**Comment by YangXiaozhou** [comment]
Currently the reason why it is not supported is not because DataProcessor can't undo undone, it can. But it is the "can only undo once" mechanism that is preventing undo undone to be carried out. That's why we see "you can only undo once" response when I try to undo a undone.

**Comment by YangXiaozhou** [comment]
@kevin-christian is this solved?

**Comment by kevin-christian** [comment]
yea it is solved
