### ISSUE TITLE
some system testing for add, delete, show doesn't work

### ISSUE THREAD

**Issue by ChunhanYu** [cs2103jan2015-f10-3c/main#291]
@YangXiaozhou 
@kevin-christian 
@angelitasasmita

**Comment by angiesasmita** [comment]
is it because of format changes?

**Comment by YangXiaozhou** [comment]
some are due to format changes,
some are due to the date changes. e.g "show today" will fail coz "today" at the time writing the system test is not "today" of today.

**Comment by angiesasmita** [comment]
we should to linh about this. I'm afraid we're get penalised when our testing does not work

**Comment by YangXiaozhou** [comment]
system testing is not checked at V0.4 wah? i thought

**Comment by angiesasmita** [comment]
idk le hahaha
