### ISSUE TITLE
after "done" a floating task, it still shows up in floating task

### ISSUE THREAD

**Issue by YangXiaozhou** [cs2103jan2015-f10-3c/main#293]
Okay, I've checked. The completeStatus of the task is updated to true. So when type in "show done", this task will correctly appear in the list. However, when type in "show float", this task will also be in the list.

**Comment by angiesasmita** [comment]
I think it's loading bug. lemme check

**Comment by angiesasmita** [comment]
my problem is not that it does show in show float. but it marks more than one task. plus cant undo the marking.

**Comment by angiesasmita** [comment]
oh nvm what i said. i'm not so sure what happens

**Comment by angiesasmita** [comment]
okay fixed
