### ISSUE TITLE
User Manual - Testing

### ISSUE THREAD

**Issue by angiesasmita** [cs2103jan2015-f10-3c/main#302]
Write in this issue things need to be taken note of. @kevin-christian @ChunhanYu @YangXiaozhou 
1. System test for "addDefault" the expected case must be change into the testing date to pass the test

**Comment by angiesasmita** [comment]
plus expected display

**Comment by YangXiaozhou** [comment]
2 System test for "show today", the expected display must be change into the testing date to pass the test

**Comment by YangXiaozhou** [comment]
3 System test for "show tomorrow", the expected display must be change into the date of testing date's tomorrow to pass the test

**Comment by YangXiaozhou** [comment]
4 System test for "show this week", the expected display must be change tasks within the week of the testing date to pass the test

**Comment by YangXiaozhou** [comment]
5 System test for "show this month", the expected display must be change tasks within the month of the testing date to pass the test

**Comment by angiesasmita** [comment]
1. for save load testing, save.txt will be created at the same directory as the .exe file

**Comment by angiesasmita** [comment]
1. for directoryCheck test, change the test with valid local directory

**Comment by angiesasmita** [comment]
testing environment: "microsoft visual studio unit testing framework"
